name: "mdbook binary"
description: "setup mdbook."
author: "maxu"

runs:
    using: "composite"
    steps:
      - id: install-mdbook-binary
        run: |
            echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
            echo "ls -al && ls -al .."
            cargo run
        shell: bash

branding:
    icon: "book-open"
    color: "yellow"
