name: "mdbook binary"
description: "setup mdbook."
author: "maxu"
inputs:
    mdbookVersion:
        description: "The mdbook version to and use. Example: 0.4.7"
        required: false
        default: "latest"

runs:
    using: "node12"
    main: "lib/index.js"

    using: "composite"
    steps:
      - id: random-number-generator
        run: echo "::set-output name=random-id::$(echo $RANDOM)"
        shell: bash

branding:
    icon: "book-open"
    color: "yellow"
