name: "mdbook binary"
description: "setup mdbook."
author: "maxu"

runs:
    using: "composite"
    steps:
      - id: install mdbook binary
        run: cargo run
        shell: bash

branding:
    icon: "book-open"
    color: "yellow"
